# Generated by Django 4.2.2 on 2025-04-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact',
        ),
        migrations.AddField(
            model_name='disease',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='eye_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Technician', 'Technician'), ('Receptionist', 'Receptionist')], max_length=50),
        ),
    ]
