# Generated by Django 4.2.2 on 2025-04-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_patient_gender_alter_patient_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disease'),
        ),
    ]
