# Generated by Django 4.2.2 on 2025-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_patient_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=100),
        ),
    ]
