# Generated by Django 4.2.2 on 2025-05-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_contact_staff_occupation_remove_staff_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='image_url',
        ),
    ]
